import { TVariantsListItemArr } from "@/components/VariantsList/types";

export const surveyQuestionsArr: Record<"form1" | "form2" | "form3" | "form4" | "form5" | "form6" | "form7" | "form8" | "form9", string> = {
    form1: "How long have you been using cryptocurrencies?",
    form2: "What cryptocurrencies have you used?",
    form3: "For what purposes did you use cryptocurrency?",
    form4: "Do you use crypto exchanges to store your personal funds?",
    form5: "What wallets have you used before?",
    form6: "How did you find out about Flem Wallet?",
    form7: "Do you have NFT tokens?",
    form8: "Would you like to participate in the Flem Wallet Preview Program?",
    form9: "Select the currency in which you want to receive the airdrop:",
};

export const surveyAnswersArr: Record<"form1" | "form2" | "form3" | "form4" | "form5" | "form6" | "form7" | "form8" | "form9", TVariantsListItemArr> = {
    form1: [
        {
            id: "survey-answer1-1",
            type: "radio",
            name: "survey-question1",
            label: "It's my first experience.",
        },
        {
            id: "survey-answer1-2",
            type: "radio",
            name: "survey-question1",
            label: "Already used cryptocurrency for personal purposes.",
        },
        {
            id: "survey-answer1-3",
            type: "radio",
            name: "survey-question1",
            label: "Use cryptocurrency on a regular basis.",
        },
        {
            id: "survey-answer1-4",
            type: "radio",
            name: "survey-question1",
            label: "Use cryptocurrency and get profit from it.",
        },
    ],
    form2: [
        {
            id: "survey-answer2-1",
            type: "checkbox",
            name: "survey-question2",
            label: "Bitcoin (BTC)",
        },
        {
            id: "survey-answer2-2",
            type: "checkbox",
            name: "survey-question2",
            label: "Ethereum (ETH)",
        },
        {
            id: "survey-answer2-3",
            type: "checkbox",
            name: "survey-question2",
            label: "Tether ERC20 (USDT)",
        },
        {
            id: "survey-answer2-4",
            type: "checkbox",
            name: "survey-question2",
            label: "Binance Coin (BNB)",
        },
        {
            id: "survey-answer2-5",
            type: "checkbox",
            name: "survey-question2",
            label: "Dogecoin (DOGE)",
        },
        {
            id: "survey-answer2-6",
            type: "checkbox",
            name: "survey-question2",
            label: "Solana (SOL)",
        },
        {
            id: "survey-answer2-7",
            type: "checkbox",
            name: "survey-question2",
            label: "Litecoin (LTC)",
        },
        {
            id: "survey-answer2-8",
            type: "checkbox",
            name: "survey-question2",
            label: "Monero (XMR)",
        },
        {
            id: "survey-answer2-9",
            type: "checkbox",
            name: "survey-question2",
            label: "Dash (DASH)",
        },
        {
            id: "survey-answer2-10",
            type: "checkbox",
            name: "survey-question2",
            label: "Other currencies",
        },
    ],
    form3: [
        {
            id: "survey-answer3-1",
            type: "checkbox",
            name: "survey-question3",
            label: "To pay for services.",
        },
        {
            id: "survey-answer3-2",
            type: "checkbox",
            name: "survey-question3",
            label: "To purchase digital goods.",
        },
        {
            id: "survey-answer3-3",
            type: "checkbox",
            name: "survey-question3",
            label: "To trade on cryptocurrency exchanges.",
        },
        {
            id: "survey-answer3-4",
            type: "checkbox",
            name: "survey-question3",
            label: "For other purposes.",
        },
    ],
    form4: [
        {
            id: "survey-answer4-1",
            type: "radio",
            name: "survey-question4",
            label: "Yes, I use.",
        },
        {
            id: "survey-answer4-2",
            type: "radio",
            name: "survey-question4",
            label: "I prefer cold wallets.",
        },
        {
            id: "survey-answer4-3",
            type: "radio",
            name: "survey-question4",
            label: "I prefer desktop software or mobile app.",
        },
        {
            id: "survey-answer4-4",
            type: "radio",
            name: "survey-question4",
            label: "I don't have any funds in cryptocurrency.",
        },
    ],
    form5: [
        {
            id: "survey-answer5-1",
            type: "checkbox",
            name: "survey-question5",
            label: "Trust Wallet",
        },
        {
            id: "survey-answer5-2",
            type: "checkbox",
            name: "survey-question5",
            label: "Coinbase Wallet",
        },
        {
            id: "survey-answer5-3",
            type: "checkbox",
            name: "survey-question5",
            label: "Electrum",
        },
        {
            id: "survey-answer5-4",
            type: "checkbox",
            name: "survey-question5",
            label: "Metamask",
        },
        {
            id: "survey-answer5-5",
            type: "checkbox",
            name: "survey-question5",
            label: "Exodus",
        },
        {
            id: "survey-answer5-6",
            type: "checkbox",
            name: "survey-question5",
            label: "Mycelium",
        },
        {
            id: "survey-answer5-7",
            type: "checkbox",
            name: "survey-question5",
            label: "Blockchain Wallet",
        },
        {
            id: "survey-answer5-8",
            type: "checkbox",
            name: "survey-question5",
            label: "Crypto.com",
        },
        {
            id: "survey-answer5-9",
            type: "checkbox",
            name: "survey-question5",
            label: "Atomic Wallet",
        },
        {
            id: "survey-answer5-10",
            type: "checkbox",
            name: "survey-question5",
            label: "Other wallet",
        },
    ],
    form6: [
        {
            id: "survey-answer6-1",
            type: "radio",
            name: "survey-question6",
            label: "Affiliate advertising in social networks.",
        },
        {
            id: "survey-answer6-2",
            type: "radio",
            name: "survey-question6",
            label: "Video reviews on YouTube.",
        },
        {
            id: "survey-answer6-3",
            type: "radio",
            name: "survey-question6",
            label: "From colleagues, friends, etc.",
        },
        {
            id: "survey-answer6-4",
            type: "radio",
            name: "survey-question6",
            label: "Other informational source.",
        },
    ],
    form7: [
        {
            id: "survey-answer7-1",
            type: "radio",
            name: "survey-question7",
            label: "Yes, I have several collections of tokens.",
        },
        {
            id: "survey-answer7-2",
            type: "radio",
            name: "survey-question7",
            label: "Yes, I have a few tokens.",
        },
        {
            id: "survey-answer7-3",
            type: "radio",
            name: "survey-question7",
            label: "I don’t have NFT.",
        },
        {
            id: "survey-answer7-4",
            type: "radio",
            name: "survey-question7",
            label: "What is NFT?",
        },
    ],
    form8: [
        {
            id: "survey-answer8-1",
            type: "radio",
            name: "survey-question8",
            label: "Yes, sure.",
        },
        {
            id: "survey-answer8-2",
            type: "radio",
            name: "survey-question8",
            label: "No, thanks.",
        },
    ],
    form9: [
        {
            id: "survey-answer9-1",
            type: "radio",
            name: "survey-question9",
            label: "Bitcoin (BTC)",
        },
        {
            id: "survey-answer9-2",
            type: "radio",
            name: "survey-question9",
            label: "Ethereum (ETH)",
        },
        {
            id: "survey-answer9-3",
            type: "radio",
            name: "survey-question9",
            label: "Tether ERC20 (USDT)",
        },
        {
            id: "survey-answer9-4",
            type: "radio",
            name: "survey-question9",
            label: "Binance Coin (BNB)",
        },
        {
            id: "survey-answer9-5",
            type: "radio",
            name: "survey-question9",
            label: "Ripple (XLM)",
        },
        {
            id: "survey-answer9-6",
            type: "radio",
            name: "survey-question9",
            label: "Solana (SOL)",
        },
        {
            id: "survey-answer9-7",
            type: "radio",
            name: "survey-question9",
            label: "Litecoin (LTC)",
        },
        {
            id: "survey-answer9-8",
            type: "radio",
            name: "survey-question9",
            label: "Monero (XMR)",
        },
        {
            id: "survey-answer9-9",
            type: "radio",
            name: "survey-question9",
            label: "Dash (DASH)",
        },
        {
            id: "survey-answer9-10",
            type: "radio",
            name: "survey-question9",
            label: "Tron (TRX)",
        },
    ],
};
