import type { TMainRateItemArr } from "./types";

import {
    algorandALGO,
    avalancheAVAX,
    binanceCoinBNB,
    bitcoinBTC,
    cardanoADA,
    chainlinkLINK,
    dogecoinDOGE,
    ethereumETH,
    litecoinLTC,
    polkadotDOT,
    polygonMATIC,
    solanaSOL,
    terraLUNA,
    xrpXRP,
} from "@/data/pages/currencies-icons";

// * Data
export const mainRateItemArr: TMainRateItemArr = [
    {
        id: "main-bitcoin-rate",
        imgPath: bitcoinBTC,
        imgAlt: "bitcoin-BTC",
        title: "Bitcoin (BTC)",
        apiLink: "wss://stream.binance.com:9443/ws/btcusdt@trade",
    },
    {
        id: "main-ethereum-rate",
        imgPath: ethereumETH,
        imgAlt: "ethereum-ETH",
        title: "Ethereum (ETH)",
        apiLink: "wss://stream.binance.com:9443/ws/ethusdt@trade",
    },
    {
        id: "main-binance-coin-rate",
        imgPath: binanceCoinBNB,
        imgAlt: "binance-coin-BNB",
        title: "Binance Coin (BNB)",
        apiLink: "wss://stream.binance.com:9443/ws/bnbusdt@trade",
    },
    {
        id: "main-solana-rate",
        imgPath: solanaSOL,
        imgAlt: "solana-SOL",
        title: "Solana (SOL)",
        apiLink: "wss://stream.binance.com:9443/ws/solusdt@trade",
    },
    {
        id: "main-cardano-rate",
        imgPath: cardanoADA,
        imgAlt: "cardano-ADA",
        title: "Cardano (ADA)",
        apiLink: "wss://stream.binance.com:9443/ws/adausdt@trade",
    },
    {
        id: "main-xrp-rate",
        imgPath: xrpXRP,
        imgAlt: "xrp-XRP",
        title: "XRP (XRP)",
        apiLink: "wss://stream.binance.com:9443/ws/xrpusdt@trade",
    },
    {
        id: "main-terra-rate",
        imgPath: terraLUNA,
        imgAlt: "terra-LUNA",
        title: "Terra (LUNA)",
        apiLink: "wss://stream.binance.com:9443/ws/lunausdt@trade",
    },
    {
        id: "main-polkadot-rate",
        imgPath: polkadotDOT,
        imgAlt: "polkadot-DOT",
        title: "Polkadot (DOT)",
        apiLink: "wss://stream.binance.com:9443/ws/dotusdt@trade",
    },
    {
        id: "main-avalanche-rate",
        imgPath: avalancheAVAX,
        imgAlt: "avalanche-AVAX",
        title: "Avalanche (AVAX)",
        apiLink: "wss://stream.binance.com:9443/ws/avaxusdt@trade",
    },
    {
        id: "main-dogecoin-rate",
        imgPath: dogecoinDOGE,
        imgAlt: "dogecoin-DOGE",
        title: "Dogecoin (DOGE)",
        apiLink: "wss://stream.binance.com:9443/ws/dogeusdt@trade",
    },
    {
        id: "main-polygon-rate",
        imgPath: polygonMATIC,
        imgAlt: "polygon-MATIC",
        title: "Polygon (MATIC)",
        apiLink: "wss://stream.binance.com:9443/ws/maticusdt@trade",
    },
    {
        id: "main-chainlink-rate",
        imgPath: chainlinkLINK,
        imgAlt: "chainlink-LINK",
        title: "Chainlink (LINK)",
        apiLink: "wss://stream.binance.com:9443/ws/linkusdt@trade",

    },
    {
        id: "main-algorand-rate",
        imgPath: algorandALGO,
        imgAlt: "algorand-ALGO",
        title: "Algorand (ALGO)",
        apiLink: "wss://stream.binance.com:9443/ws/algousdt@trade",
    },
    {
        id: "main-litecoin-rate",
        imgPath: litecoinLTC,
        imgAlt: "litecoin-LTC",
        title: "Litecoin (LTC)",
        apiLink: "wss://stream.binance.com:9443/ws/ltcusdt@trade",
    },
];
