import type { TMainAssetsItemArr } from "./types";

import {
    aaveAAVE,
    algorandALGO,
    avalancheAVAX,
    axieInfinityAXS,
    binanceCoinBNB,
    bitcoinBTC,
    bitcoinCashBCH,
    cardanoADA,
    chainlinkLINK,
    cosmosATOM,
    cronosCRO,
    daiDAI,
    dogecoinDOGE,
    elrondEGLD,
    ethereumETH,
    ethereumClassicETC,
    fantomFTM,
    filecoinFIL,
    ftxTokenFTT,
    hederaHBAR,
    heliumHNT,
    internetComputerICP,
    iotaMIOTA,
    litecoinLTC,
    moneroXMR,
    nearNEAR,
    polkadotDOT,
    polygonMATIC,
    shibainuSHIB,
    solanaSOL,
    stellarXLM,
    terraLUNA,
    tetherUSDT,
    tezosXTZ,
    sandboxSAND,
    thetaTHETA,
    tronTRX,
    veChainVET,
    wrappedBitcoinWBTC,
    xrpXRP,
} from "@/data/pages/currencies-icons";

// * In id prop use AllCurNames enum
export const mainAssetItemArr: TMainAssetsItemArr = [
    {
        id: "bitcoin-tooltip",
        disabled: false,
        imgPath: bitcoinBTC,
        imgAlt: "bitcoin-BTC",
        title: "Bitcoin (BTC)",
    },
    {
        id: "ethereum-tooltip",
        disabled: false,
        imgPath: ethereumETH,
        imgAlt: "ethereum-ETH",
        title: "Ethereum (ETH)",
    },
    {
        id: "binance-coin-tooltip",
        disabled: false,
        imgPath: binanceCoinBNB,
        imgAlt: "binance-coin-BNB",
        title: "Binance Coin (BNB)",
    },
    {
        id: "tether-tooltip",
        disabled: false,
        imgPath: tetherUSDT,
        imgAlt: "tether-USDT",
        title: "Tether (USDT)",
    },
    {
        id: "solana-tooltip",
        disabled: false,
        imgPath: solanaSOL,
        imgAlt: "solana-SOL",
        title: "Solana (SOL)",
    },
    {
        id: "cardano-tooltip",
        disabled: false,
        imgPath: cardanoADA,
        imgAlt: "cardano-ADA",
        title: "Cardano (ADA)",
    },
    {
        id: "xrp-tooltip",
        disabled: false,
        imgPath: xrpXRP,
        imgAlt: "xrp-XRP",
        title: "XRP (XRP)",
    },
    {
        id: "terra-tooltip",
        disabled: false,
        imgPath: terraLUNA,
        imgAlt: "terra-LUNA",
        title: "Terra (LUNA)",
    },
    {
        id: "polkadot-tooltip",
        disabled: false,
        imgPath: polkadotDOT,
        imgAlt: "polkadot-DOT",
        title: "Polkadot (DOT)",
    },
    {
        id: "avalanche-tooltip",
        disabled: false,
        imgPath: avalancheAVAX,
        imgAlt: "avalanche-AVAX",
        title: "Avalanche (AVAX)",
    },
    {
        id: "dogecoin-tooltip",
        disabled: false,
        imgPath: dogecoinDOGE,
        imgAlt: "dogecoin-DOGE",
        title: "Dogecoin (DOGE)",
    },
    {
        id: "shiba-inu-tooltip",
        disabled: false,
        imgPath: shibainuSHIB,
        imgAlt: "shiba-inu-SHIB",
        title: "Shiba Inu (SHIB)",
    },
    {
        id: "polygon-tooltip",
        disabled: false,
        imgPath: polygonMATIC,
        imgAlt: "polygon-MATIC",
        title: "Polygon (MATIC)",
    },
    {
        id: "cronos-tooltip",
        disabled: false,
        imgPath: cronosCRO,
        imgAlt: "cronos-CRO",
        title: "Cronos (CRO)",
    },
    {
        id: "wrapped-bitcoin-tooltip",
        disabled: false,
        imgPath: wrappedBitcoinWBTC,
        imgAlt: "wrapped-bitcoin-WBTC",
        title: "Wrapped Bitcoin (WBTC)",
    },
    {
        id: "algorand-tooltip",
        disabled: false,
        imgPath: algorandALGO,
        imgAlt: "algorand-ALGO",
        title: "Algorand (ALGO)",
    },
    {
        id: "litecoin-tooltip",
        disabled: false,
        imgPath: litecoinLTC,
        imgAlt: "litecoin-LTC",
        title: "Litecoin (LTC)",
    },
    {
        id: "chainlink-tooltip",
        disabled: false,
        imgPath: chainlinkLINK,
        imgAlt: "chainlink-LINK",
        title: "Chainlink (LINK)",
    },
    {
        id: "dai-tooltip",
        disabled: false,
        imgPath: daiDAI,
        imgAlt: "dai-DAI",
        title: "Dai (DAI)",
    },
    {
        id: "bitcoin-cash-tooltip",
        disabled: false,
        imgPath: bitcoinCashBCH,
        imgAlt: "bitcoin-cash-BCH",
        title: "Bitcoin Cash (BCH)",
    },
    {
        id: "fantom-tooltip",
        disabled: false,
        imgPath: fantomFTM,
        imgAlt: "fantom-FTM",
        title: "Fantom (FTM)",
    },
    {
        id: "axie-infinity-tooltip",
        disabled: false,
        imgPath: axieInfinityAXS,
        imgAlt: "axie-infinity-AXS",
        title: "Axie Infinity (AXS)",
    },
    {
        id: "tron-tooltip",
        disabled: false,
        imgPath: tronTRX,
        imgAlt: "tron-TRX",
        title: "Tron (TRX)",
    },
    {
        id: "stellar-tooltip",
        disabled: false,
        imgPath: stellarXLM,
        imgAlt: "stellar-XLM",
        title: "Stellar (XLM)",
    },
    {
        id: "near-protocol-tooltip",
        disabled: false,
        imgPath: nearNEAR,
        imgAlt: "near-protocol-NEAR",
        title: "Near (NEAR)",
    },
    {
        id: "ftx-token-tooltip",
        disabled: false,
        imgPath: ftxTokenFTT,
        imgAlt: "ftx-token-FTT",
        title: "FTX Token (FTT)",
    },
    {
        id: "cosmos-tooltip",
        disabled: false,
        imgPath: cosmosATOM,
        imgAlt: "cosmos-ATOM",
        title: "Cosmos (ATOM)",
    },
    {
        id: "ve-chain-tooltip",
        disabled: false,
        imgPath: veChainVET,
        imgAlt: "ve-chain-VET",
        title: "Ve Chain (VET)",
    },
    {
        id: "hedera-tooltip",
        disabled: false,
        imgPath: hederaHBAR,
        imgAlt: "hedera-HBAR",
        title: "Hedera (HBAR)",
    },
    {
        id: "the-sandbox-tooltip",
        disabled: false,
        imgPath: sandboxSAND,
        imgAlt: "the-sandbox-SAND",
        title: "The Sandbox (SAND)",
    },
    {
        id: "filecoin-tooltip",
        disabled: false,
        imgPath: filecoinFIL,
        imgAlt: "filecoin-FIL",
        title: "Filecoin (FIL)",
    },
    {
        id: "internet-computer-tooltip",
        disabled: false,
        imgPath: internetComputerICP,
        imgAlt: "internet-computer-ICP",
        title: "Internet Computer (ICP)",
    },
    {
        id: "theta-network-tooltip",
        disabled: false,
        imgPath: thetaTHETA,
        imgAlt: "theta-network-THETA",
        title: "Theta Network (THETA)",
    },
    {
        id: "elrond-tooltip",
        disabled: false,
        imgPath: elrondEGLD,
        imgAlt: "elrond-EGLD",
        title: "Elrond (EGLD)",
    },
    {
        id: "ethereum-classic-tooltip",
        disabled: true,
        imgPath: ethereumClassicETC,
        imgAlt: "ethereum-classic-ETC",
        title: "Ethereum Classic (ETC)",
    },
    {
        id: "monero-tooltip",
        disabled: true,
        imgPath: moneroXMR,
        imgAlt: "monero-XMR",
        title: "Monero (XMR)",
    },
    {
        id: "helium-tooltip",
        disabled: false,
        imgPath: heliumHNT,
        imgAlt: "helium-HNT",
        title: "Helium (HNT)",
    },
    {
        id: "tezos-tooltip",
        disabled: false,
        imgPath: tezosXTZ,
        imgAlt: "tezos-XTZ",
        title: "Tezos (XTZ)",
    },
    {
        id: "iota-tooltip",
        disabled: false,
        imgPath: iotaMIOTA,
        imgAlt: "iota-MIOTA",
        title: "IOTA (MIOTA)",
    },
    {
        id: "aave-tooltip",
        disabled: false,
        imgPath: aaveAAVE,
        imgAlt: "aave-AAVE",
        title: "Aave (AAVE)",
    },
];
