import { AllCurFullNames } from "@/types/data/currencies";
import type { TMainAssetsItemArr } from "./types";

import {
    aaveAAVE,
    algorandALGO,
    avalancheAVAX,
    axieInfinityAXS,
    binanceCoinBNB,
    bitcoinBTC,
    bitcoinCashBCH,
    cardanoADA,
    chainlinkLINK,
    cosmosATOM,
    cronosCRO,
    daiDAI,
    dogecoinDOGE,
    elrondEGLD,
    ethereumETH,
    ethereumClassicETC,
    fantomFTM,
    filecoinFIL,
    ftxTokenFTT,
    hederaHBAR,
    heliumHNT,
    internetComputerICP,
    iotaMIOTA,
    litecoinLTC,
    moneroXMR,
    nearNEAR,
    polkadotDOT,
    polygonMATIC,
    shibainuSHIB,
    solanaSOL,
    stellarXLM,
    terraLUNA,
    tetherUSDT,
    tezosXTZ,
    sandboxSAND,
    thetaTHETA,
    tronTRX,
    veChainVET,
    wrappedBitcoinWBTC,
    xrpXRP,
} from "@/data/pages/currencies-icons";

// * In id prop use AllCurShortNames enum
export const mainAssetItemArr: TMainAssetsItemArr = [
    {
        id: "bitcoin-tooltip",
        disabled: false,
        imgPath: bitcoinBTC,
        imgAlt: "bitcoin-BTC",
        title: AllCurFullNames.bitcoin,
    },
    {
        id: "ethereum-tooltip",
        disabled: false,
        imgPath: ethereumETH,
        imgAlt: "ethereum-ETH",
        title: AllCurFullNames.ethereum
    },
    {
        id: "binance-coin-tooltip",
        disabled: false,
        imgPath: binanceCoinBNB,
        imgAlt: "binance-coin-BNB",
        title: AllCurFullNames.binanceCoin,
    },
    {
        id: "tether-tooltip",
        disabled: false,
        imgPath: tetherUSDT,
        imgAlt: "tether-USDT",
        title: AllCurFullNames.tether,
    },
    {
        id: "solana-tooltip",
        disabled: false,
        imgPath: solanaSOL,
        imgAlt: "solana-SOL",
        title: AllCurFullNames.solana,
    },
    {
        id: "cardano-tooltip",
        disabled: false,
        imgPath: cardanoADA,
        imgAlt: "cardano-ADA",
        title: AllCurFullNames.cardano,
    },
    {
        id: "xrp-tooltip",
        disabled: false,
        imgPath: xrpXRP,
        imgAlt: "ripple-XRP",
        title: AllCurFullNames.xrp,
    },
    {
        id: "terra-tooltip",
        disabled: false,
        imgPath: terraLUNA,
        imgAlt: "terra-LUNA",
        title: AllCurFullNames.terra,
    },
    {
        id: "polkadot-tooltip",
        disabled: false,
        imgPath: polkadotDOT,
        imgAlt: "polkadot-DOT",
        title: AllCurFullNames.polkadot,
    },
    {
        id: "avalanche-tooltip",
        disabled: false,
        imgPath: avalancheAVAX,
        imgAlt: "avalanche-AVAX",
        title: AllCurFullNames.avalanche,
    },
    {
        id: "dogecoin-tooltip",
        disabled: false,
        imgPath: dogecoinDOGE,
        imgAlt: "dogecoin-DOGE",
        title: AllCurFullNames.dogecoin,
    },
    {
        id: "shiba-inu-tooltip",
        disabled: false,
        imgPath: shibainuSHIB,
        imgAlt: "shiba-inu-SHIB",
        title: AllCurFullNames.shibainu,
    },
    {
        id: "polygon-tooltip",
        disabled: false,
        imgPath: polygonMATIC,
        imgAlt: "polygon-MATIC",
        title: AllCurFullNames.polygon,
    },
    {
        id: "cronos-tooltip",
        disabled: false,
        imgPath: cronosCRO,
        imgAlt: "cronos-CRO",
        title: AllCurFullNames.cronos,
    },
    {
        id: "wrapped-bitcoin-tooltip",
        disabled: false,
        imgPath: wrappedBitcoinWBTC,
        imgAlt: "wrapped-bitcoin-WBTC",
        title: AllCurFullNames.wrappedBitcoin,
    },
    {
        id: "algorand-tooltip",
        disabled: false,
        imgPath: algorandALGO,
        imgAlt: "algorand-ALGO",
        title: AllCurFullNames.algorand,
    },
    {
        id: "litecoin-tooltip",
        disabled: false,
        imgPath: litecoinLTC,
        imgAlt: "litecoin-LTC",
        title: AllCurFullNames.litecoin,
    },
    {
        id: "chainlink-tooltip",
        disabled: false,
        imgPath: chainlinkLINK,
        imgAlt: "chainlink-LINK",
        title: AllCurFullNames.chainlink,
    },
    {
        id: "dai-tooltip",
        disabled: false,
        imgPath: daiDAI,
        imgAlt: "dai-DAI",
        title: AllCurFullNames.dai,
    },
    {
        id: "bitcoin-cash-tooltip",
        disabled: false,
        imgPath: bitcoinCashBCH,
        imgAlt: "bitcoin-cash-BCH",
        title: AllCurFullNames.bitcoinCash,
    },
    {
        id: "fantom-tooltip",
        disabled: false,
        imgPath: fantomFTM,
        imgAlt: "fantom-FTM",
        title: AllCurFullNames.fantom,
    },
    {
        id: "axie-infinity-tooltip",
        disabled: false,
        imgPath: axieInfinityAXS,
        imgAlt: "axie-infinity-AXS",
        title: AllCurFullNames.axieInfinity,
    },
    {
        id: "tron-tooltip",
        disabled: false,
        imgPath: tronTRX,
        imgAlt: "tron-TRX",
        title: AllCurFullNames.tron,
    },
    {
        id: "stellar-tooltip",
        disabled: false,
        imgPath: stellarXLM,
        imgAlt: "stellar-XLM",
        title: AllCurFullNames.stellar,
    },
    {
        id: "near-protocol-tooltip",
        disabled: false,
        imgPath: nearNEAR,
        imgAlt: "near-protocol-NEAR",
        title: AllCurFullNames.nearProtocol,
    },
    {
        id: "ftx-token-tooltip",
        disabled: false,
        imgPath: ftxTokenFTT,
        imgAlt: "ftx-token-FTT",
        title: AllCurFullNames.ftxToken,
    },
    {
        id: "cosmos-tooltip",
        disabled: false,
        imgPath: cosmosATOM,
        imgAlt: "cosmos-ATOM",
        title: AllCurFullNames.cosmos,
    },
    {
        id: "ve-chain-tooltip",
        disabled: false,
        imgPath: veChainVET,
        imgAlt: "ve-chain-VET",
        title: AllCurFullNames.veChain,
    },
    {
        id: "hedera-tooltip",
        disabled: false,
        imgPath: hederaHBAR,
        imgAlt: "hedera-HBAR",
        title: AllCurFullNames.hedera,
    },
    {
        id: "the-sandbox-tooltip",
        disabled: false,
        imgPath: sandboxSAND,
        imgAlt: "the-sandbox-SAND",
        title: AllCurFullNames.theSandbox,
    },
    {
        id: "filecoin-tooltip",
        disabled: false,
        imgPath: filecoinFIL,
        imgAlt: "filecoin-FIL",
        title: AllCurFullNames.filecoin,
    },
    {
        id: "internet-computer-tooltip",
        disabled: false,
        imgPath: internetComputerICP,
        imgAlt: "internet-computer-ICP",
        title: AllCurFullNames.internetComputer,
    },
    {
        id: "theta-network-tooltip",
        disabled: false,
        imgPath: thetaTHETA,
        imgAlt: "theta-network-THETA",
        title: AllCurFullNames.thetaNetwork,
    },
    {
        id: "elrond-tooltip",
        disabled: false,
        imgPath: elrondEGLD,
        imgAlt: "elrond-EGLD",
        title: AllCurFullNames.elrond,
    },
    {
        id: "ethereum-classic-tooltip",
        disabled: true,
        imgPath: ethereumClassicETC,
        imgAlt: "ethereum-classic-ETC",
        title: AllCurFullNames.ethereumClassic,
    },
    {
        id: "monero-tooltip",
        disabled: true,
        imgPath: moneroXMR,
        imgAlt: "monero-XMR",
        title: AllCurFullNames.monero,
    },
    {
        id: "helium-tooltip",
        disabled: false,
        imgPath: heliumHNT,
        imgAlt: "helium-HNT",
        title: AllCurFullNames.helium,
    },
    {
        id: "tezos-tooltip",
        disabled: false,
        imgPath: tezosXTZ,
        imgAlt: "tezos-XTZ",
        title: AllCurFullNames.tezos,
    },
    {
        id: "iota-tooltip",
        disabled: false,
        imgPath: iotaMIOTA,
        imgAlt: "iota-MIOTA",
        title: AllCurFullNames.iota,
    },
    {
        id: "aave-tooltip",
        disabled: false,
        imgPath: aaveAAVE,
        imgAlt: "aave-AAVE",
        title: AllCurFullNames.aave,
    },
];
