import type { Metadata } from "next";

import "../public/scss/globals.scss";
import localFont from "next/font/local";

const titilliumWeb = localFont({
    src: [
        {
            path: "../public/fonts/TitilliumWeb-Light.woff2",
            weight: "300",
            style: "normal",
        },
        {
            path: "../public/fonts/TitilliumWeb-Regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../public/fonts/TitilliumWeb-SemiBold.woff2",
            weight: "600",
            style: "normal",
        },
        {
            path: "../public/fonts/TitilliumWeb-Bold.woff2",
            weight: "700",
            style: "normal",
        },
    ],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={titilliumWeb.className}>
                <div className="wrapper">{children}</div>
            </body>
        </html>
    );
}
