import { clockIcon, dropIcon, exportIcon, importIcon } from "@/data/pages/ui-icons";
import { THistoryTableItemArr } from "./types";
import { swapHorizontalIcon } from "@/data/pages/web3-icons";

export const historyTableItemArr: THistoryTableItemArr = [
    {
        id: 1,
        operType: "Replenish",
        curName: "Binance Coin (BNB)",
        curSign: "BNB",
        amount: 0.12345678,
        transactionStatus: "Complete",
        transactionId: 455655,
        date: "07.07.2023 17:17",
        recipient: "bc1uf5tdn87k2uz7r2kl5zrfww362ch3746lq5vse7",
        modifClass: "dashboard-log-item--get",
        svgIcon: importIcon,
    },
    {
        id: 2,
        operType: "Withdraw",
        curName: "Tether (USDT)",
        curSign: "USDT",
        amount: 5.25,
        transactionStatus: "Complete",
        transactionId: 547676,
        date: "07.07.2023 17:17",
        recipient: "0x1uf5tdn87k2uz7r2kl5zrfww362ch3746lq5vse7",
        modifClass: "dashboard-log-item--send",
        svgIcon: exportIcon,
    },
    {
        id: 3,
        operType: "Exchange",
        curName: "Bitcoin (BTC)",
        curSign: "BTC",
        amount: 0.12345678,
        transactionStatus: "Complete",
        transactionId: 455655,
        date: "07.07.2023 17:17",
        recipient: "bc1uf5tdn87k2uz7r2kl5zrfww362ch3746lq5vse7",
        modifClass: "dashboard-log-item--info",
        svgIcon: swapHorizontalIcon,
    },
    {
        id: 4,
        operType: "Airdrop",
        curName: "Tether (USDT)",
        curSign: "USDT",
        amount: 5.25,
        transactionStatus: "Pending",
        transactionId: 547676,
        date: "07.07.2023 17:17",
        recipient: "0x1uf5tdn87k2uz7r2kl5zrfww362ch3746lq5vse7",
        modifClass: "dashboard-log-item--info",
        svgIcon: dropIcon,
    },
    {
        id: 5,
        operType: "Replenish",
        curName: "Bitcoin (BTC)",
        curSign: "BTC",
        amount: 0.12345678,
        transactionStatus: "Complete",
        transactionId: 455655,
        date: "07.07.2023 17:17",
        recipient: "bc1uf5tdn87k2uz7r2kl5zrfww362ch3746lq5vse7",
        modifClass: "dashboard-log-item--wait",
        svgIcon: clockIcon,
    },
    {
        id: 6,
        operType: "Withdraw",
        curName: "Tether (USDT)",
        curSign: "USDT",
        amount: 5.25,
        transactionStatus: "Complete",
        transactionId: 547676,
        date: "07.07.2023 17:17",
        recipient: "0x1uf5tdn87k2uz7r2kl5zrfww362ch3746lq5vse7",
        modifClass: "dashboard-log-item--send",
        svgIcon: exportIcon,
    },
];
